# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RailsDevKev - A blog about Ruby on Rails and other WebDev Tools
email: kevin.egstorf@gmail.com
description: This is a Blog about RoR techniques
url: "http://railsdevkev.com" # the base hostname & protocol for your site
twitter_username: kevinegstorf
github_username:  kevinegstorf


# Build settings
markdown: redcarpet
permalink: /:title
